PREFIX arc: <http://purl.org/dc/elements/1.1/>
SELECT ?title ?description ?author ?date
	WHERE {
		 ?x arc:title ?title .
		 FILTER regex(?title, "construction") .
		 ?x arc:description ?description .
		 ?x arc:creator ?author .
		 ?x arc:date ?date . 
	 }